### ISSUE TITLE
List of TODOs/priorities?

### ISSUE THREAD

**Issue by slogsdon** [lfe-mug/lmug#1]
I'd love to help out as much as I can. New to LFE; not so much to BEAM-based languages.

**Comment by rvirding** [comment]
As far as I know there isn't one. I would just suggest attacking a feature you to work on. Have you worked much with lisp?

**Comment by slogsdon** [comment]
I haven't pushed any production code using a Lisp yet, but I have been trying to find one that I like. I've written some smallish experiments with Clojure and Racket.

**Comment by oubiwann** [comment]
Loooong over-due response. Finally getting back to lmug, now that [dragon](https://github.com/lfex/dragon) is becoming a thing (it will eventually use lmug -- milestones 3, 5, and  7).

If you're still interested, be sure to watch the "issues" section of the lfex/lmug repo. I'll be adding at least one ticket to track the work needed to prepare lmug for inclusion in dragon. Once some tickets (and maybe even milestones) are defined, I'll update this ticket again.

**Comment by oubiwann** [comment]
Okay, lots more tickets added as well as 3 milestones:
- https://github.com/lfe-mug/lmug/milestones

Clicking v1-v3 on that page will take you to the tickets for just that milestone (both open and closed).

At long last, this should answer the question of this ticket :-) (So I will close ...)
