### ISSUE TITLE
Add lmug-mw-atom-params 

### ISSUE THREAD

**Issue by oubiwann** [lfe-mug/lmug#16]
See https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/keyword_params.clj

**Comment by yurrriq** [comment]
I'm not sure this is advisable.
1. It's possible this could cause the VM to run out of atoms if the server is running a long time and lots of unique params are encountered.
2. The spec says param keys should be binaries.†

† We may want to adjust the spec or create `lmug-mw-binary-params` instead. I lean toward the latter. Or rather, I think `lmug` itself should enforce the spec and coerce param keys as necessary.

**Comment by oubiwann** [comment]
I did think about the atom table issue, but I've never encountered a web app will over a million unique params. Regardless, this point is still valid and should be weighed in the balance.

Your second point and footnote are very compelling.

I'll close this ticket and open one for `lmug-mw-binary-params` ...
