### ISSUE TITLE
Revert rebar.config profile changes

### ISSUE THREAD

**Issue by oubiwann** [lfe-mug/lmug#23]
In this PR:
- https://github.com/lfe-mug/lmug/pull/13

The `rebar.config` file was re-worked, but a side-effect of this has been that when rebuilding from scratch (which I do on a regular basis) everything gets downloaded when running unit tests, and I'd rather just have the unit test deps pulled down.

**Comment by yurrriq** [comment]
Do you use `lfe-version` and `lfe-clean`? I don't/never have.

**Comment by oubiwann** [comment]
Yeah, I use them when debugging. This is why I put them in the "dev" profile, since most people won't use them unless they are actually doing development on the project and need to wipe out everything or check the versions of all the major components.

**Comment by yurrriq** [comment]
:+1: #30 should address this.

**Comment by yurrriq** [comment]
Reopen if you're unsatisfied, @oubiwann.
